POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
  "username": "yanis2",
  "password": "Pass1234!",
  "email": "yanis2@mail.com"
}

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "username": "yanis2",
  "password": "Pass1234!"
}

###
### Buy tickets
POST http://localhost:8000/api/buy_tickets
Content-Type: application/json
Authorization: Token c217c667d1c686d3d8d503bdc93d7c6fa24b60ec

{
  "tickets": 5
}

###


GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json
Authorization: token xxx

###
# Submit form basique
POST http://127.0.0.1:8000/api/submit_form_basique
Content-Type: application/json
Authorization: Token xxx

{
  "brand": "Carrefour",
  "city": "Paris"
}