# Generated by Django 5.0.6 on 2024-06-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_purchase_user_alter_ticket_user_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
